### ISSUE TITLE
if post method response is z.void()

### ISSUE THREAD

**Issue by lewiscasewelltvpt** [ka2jun8/zodios-msw#4]
Hi, thanks for sharing your wrapper for zodios msw. When it comes to returning void from a post request using makeApi(), I get a Type error that Type 'void' is not assignable to type 'DefaultBodyType' in wrapper.ts. I was wondering if you had any ideas why this could be?
thanks

**Comment by ka2jun8** [comment]
If response body is empty, wouldn't the type be `z.undefined()` ?

**Comment by lewiscasewelltvpt** [comment]
Yes. Thank you!
